homework 1
Anoldyouth/Java-Telegram-Notifications pull request #1
Opened 2024-02-14 20:57 UTC by Anoldyouth

Скелет бота

https://edu.tinkoff.ru/my-activities/courses/stream/b37f2c9a-b73c-4cc8-a092-0bcbf49faac7/exam/18327/1

2024-02-22 17:54 UTC, sevolchenko approved these changes

2024-02-22 17:54 UTC, sevolchenko commented on bot/src/main/resources/application.yml
> +    name: ${BOT_SPRING_APPLICATION_NAME:bot}
Не обязательно на все значения в конфигурации вешать значения по умолчанию
Можно оставить порт, это полезно
А вот токен - точно без значения по умолчанию

2024-02-22 17:54 UTC, sevolchenko commented on scrapper/src/main/resources/application.yml
> +    enable: ${SCRAPPER_APP_SCHEDULER_ENABLE:true}
Аналогично про дефолтные значения

2024-02-22 17:54 UTC, sevolchenko commented on pom.xml
> +            <version>4.0.0</version>
Вынеси версию в проперти мавена

2024-02-22 17:54 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/BotApplication.java
> +    private ApplicationConfig applicationConfig;
А это зачем?

2024-02-22 17:54 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/util/CommandEnum.java
> +public enum CommandEnum {
В задании указано "Попробуйте сделать, что команды можно было легко добавлять и удалять."

У тебя же из за статического Enum это сделать не просто - попробуй это переписать на классы, и ты сможешь внедрить все команды в любой компонент, используя List<Command> (естественно, нужно все команды унаследовать от одного класса)

2024-02-22 17:54 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/util/Bot.java
> +    @EventListener(ApplicationReadyEvent.class)
Лучше так не делать

Создай BotConfiguration, где определишь бин бота и выполнишь нужную конфигурацию (установишь токен, выставишь лисенер и тд)

2024-02-22 17:54 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/util/action/AbstractAction.java
> +package edu.java.bot.util.action;
Разберись пожалуйста со структурой папок

util - место не для ДТО, сервисов и тд

2024-02-22 17:54 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/util/action/ChainElement.java
> +    static <T extends ChainElement<T>> T buildChain(List<T> elements, T lastElement) {
Не хорошо, когда элемент цепочки отвечает за построение цепочки (он не должен знать, что у него есть соседи) - у тебя для таких целей есть класс ActionFacade

Кстати, можно использовать лайфхак из коммента к CommandEnum) и вынести построение из статика в класс-конфигурацию

2024-02-22 17:54 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/util/action/CancelAction.java
> +public class CancelAction extends AbstractAction {
Хорошая идея сделать такую команду

Опиши, как ты собираешься реализовать отмену?

2024-02-22 17:54 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/util/action/CancelAction.java
> +        if (update.message() == null) {
У тебя во всех наследниках AbstractAction повторяется эта строчка, может вынести ее в абстрактный класс?

2024-02-22 17:54 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/util/action/TrackUrlAction.java
> +    protected Optional<ResponseData> process(Update update) {
Опиши, как ты собираешься получать ссылки для отслеживания?

То есть, какая тут пользовательская история? На данный момент вижу, что не обязательно вводить /track, чтобы добавить ссылку

2024-02-22 17:56 UTC, sevolchenko approved these changes

2024-02-22 17:56 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/BotCommandsTest.java
> +public class BotCommandsTest {
Почему только один тест? За их отсутствие мы снимаем баллы.Напиши тесты на то, что у тебя каждая команда отдает то, что ожидалось.
Напиши тесты на саму цепочку

2024-02-22 17:57 UTC, sevolchenko approved these changes

2024-02-22 18:00 UTC, sevolchenko requested changes

2024-02-22 18:00 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/BotCommandsTest.java
> +public class BotCommandsTest {
Еще почитай про подход AAA - Arrange, Act, Assert - очень упрощает написание юнитов

2024-02-22 18:00 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/BotCommandsTest.java
> +    static TelegramBot telegramBotMock;
Тесты должны быть независимыми друг от друга, не используй статик в тестах, создавай объекты

2024-02-22 18:24 UTC, Anoldyouth commented on bot/src/main/java/edu/java/bot/util/action/TrackUrlAction.java
> +    protected Optional<ResponseData> process(Update update) {
![image](https://github.com/Anoldyouth/Java-Telegram-Notifications/assets/83974142/3b0f0be0-c127-4b8d-bd62-5a234c75fb18)

Соответственно, необходимо хранить состояние о предыдущем действии пользователя, что пока не сделать без БД

2024-02-22 18:28 UTC, Anoldyouth commented on bot/src/main/java/edu/java/bot/util/action/CancelAction.java
> +        if (update.message() == null) {
Не во всех
Например, в UnknownCommandAction не требуется скип (и соответственно проверка), а в действияех, где анализируется вызов кнопки - идет проверка callback-а

Можно вынести в какую-то функцию, которая возвращает true/false, но меньше кода не станет

2024-02-22 18:29 UTC, Anoldyouth commented on bot/src/main/java/edu/java/bot/util/action/CancelAction.java
> +public class CancelAction extends AbstractAction {
![image](https://github.com/Anoldyouth/Java-Telegram-Notifications/assets/83974142/640b5ff8-5f4e-46f3-ad4e-a8649260d80f)

Так как у меня не /track <url> и /untrack <url>, то у пользователя должна быть возможность вернуться назад

2024-02-22 19:23 UTC, Anoldyouth commented on bot/src/main/java/edu/java/bot/util/CommandEnum.java
> +public enum CommandEnum {
Добавил в конфиги настройки цепочек
CommandEnum оставил, так как это просто справочник
Action-ы вполне себе могут существовать без него

Цепочки в конфигах - это настраиваемые точки ветвления приложения
Позже будет добавлен маппер, который будет выбирать цепочку действий по необходимости
Для данного приложения точек ветвления немного, но в теории их может быть сколь угодно много

![image](https://github.com/Anoldyouth/Java-Telegram-Notifications/assets/83974142/b20de226-ca88-44d0-bbbc-8edc76bd70b7)

2024-02-22 21:52 UTC, Anoldyouth commented on bot/src/main/java/edu/java/bot/util/Bot.java
> +    @EventListener(ApplicationReadyEvent.class)
Я поправил
Но если что-то не так - буду благодарен ссылкам на примеры
Но смотрю на запись семинара - вроде верно

2024-02-22 21:55 UTC, Anoldyouth commented on bot/src/test/java/edu/java/bot/BotCommandsTest.java
> +public class BotCommandsTest {
Он соблюдается

2024-02-22 21:56 UTC, Anoldyouth commented on bot/src/test/java/edu/java/bot/BotCommandsTest.java
> +public class BotCommandsTest {
Этот тест проверяет все команды
Единственное, что не проверил - открепление ссылки

2024-02-22 21:57 UTC, Anoldyouth commented on bot/src/test/java/edu/java/bot/BotCommandsTest.java
> +public class BotCommandsTest {
А так же каждый респонз предполагает прохождение через цепочку, частично или полностью

2024-02-23 08:06 UTC, sevolchenko requested changes

2024-02-23 08:06 UTC, sevolchenko commented on bot/src/main/resources/application.yml
> +    name: ${BOT_SPRING_APPLICATION_NAME}
Ты не так меня понял)

Убери везде env, кроме порта и телеграм-токена, их оставь, как сейчас есть

И на будущее - если я комментирую какую то строчку, не обязательно это относится к ней, это может распростроняться и на файл в целом

2024-02-23 08:06 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/BotCommandsTest.java
> +public class BotCommandsTest {
Да, но этот тест проверяет бота в целом - он зависит от правильности реализации каждого экшена и респонза, их нужно протестировать отдельно

Без этих тестов максимального балла не будет

2024-02-23 08:06 UTC, sevolchenko commented on pom.xml
> +        <paulschwarz-spring-dotenv>4.0.0</paulschwarz-spring-dotenv>
.version забыл

2024-02-23 08:06 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/configuration/Chain.java
> +public interface Chain {
Пакет configuration - только для классов с аннотацией @Configuration или @ConfigurationProperties

Тебе нужно вынести интерфейс и все его реализации куда то в другой пакет, а в пакете configuration создать что то около

Мы используем спринг и должны использовать его возможности

`
@Configuration
public class ChainConfiguration {

@Qualifier("mainChain")
@Bean
public Chain mainChain(*все action, которые понадобятся*) {
  // Создаешь Chain, в конструктор которого закидываешь все action
}

// аналогично для TrackUrlChain и UntrackChain

}
`

Для того, чтобы это заработало, тебе нужно сделать Action'ы компонентами

2024-02-23 08:06 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/dto/response/ListResponse.java
> +package edu.java.bot.dto.response;
Это не DTO, потому что в классе есть логика

2024-02-23 09:37 UTC, Anoldyouth commented on bot/src/test/java/edu/java/bot/BotCommandsTest.java
> +public class BotCommandsTest {
Это точки входа в мое приложение, которое является основой
Я как пользователь тестирую, что вот я ввел команду - получил нужный ответ
Писать тесты на action-ы и response-ы, которые мало того, что имеют простейшую логику, так и еще будут переделаны, потому что будет настроено взаимодействие сервисов - на данный момент лишняя трата времени

Также не были озвучены требования тестов, а значит мы сами решаем, какие тесты мы пишем
Я придерживаюсь мнения, что для backend-приложения должны быть протестированы точки входа, так как это важно, но нагружать их избыточными тестами не надо, иначе при каждом чихе придется переделывать половину тестов, что замедляет разработку. Тесты должны быть, но это не должно покрывать абсолютно все (да и не получится)

2024-02-23 09:40 UTC, Anoldyouth commented on bot/src/main/resources/application.yml
> +    name: ${BOT_SPRING_APPLICATION_NAME}
Я стараюсь придерживаться разработки как на прод
А это значит, что доступ к переменным должен иметь девопс, который не должен лезть в код
Как минимум из моего опыта, ты просишь сменить какие-то переменные на какой-то площадке - девопс сам настраивает через приложение развертывания переменные

2024-02-23 09:56 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/BotCommandsTest.java
> +public class BotCommandsTest {
Требования тестов озвучены были: они должны быть unit, а у тебя получились не юниты

Unit тест - тест, проверяющий работу одной функции

Даже в простейшей логике можно ошибиться, например, словить NPE в неожиданном месте или использовать некорректное поле

Насчет твоего мнения - это правильно, что перегружать приложения тестами не надо

Но пойми, что есть разные виды тестов и каждый предназначен для своей цели

У тебя не всегда может быть возможность проверить всю точку входа, потому что она может быть завязана на сторонних системах. А еще этой точки входа может и вовсе не быть.
Поэтому юниты очень важны для приложения, они отловят большую часть ошибок.

2024-02-23 10:08 UTC, sevolchenko commented on bot/src/main/resources/application.yml
> +    name: ${BOT_SPRING_APPLICATION_NAME}
В хороших проектах (а у нас именно такие) используют [Spring Cloud](https://github.com/spring-cloud/spring-cloud-config) - очень интересная штука.

По сути, ты можешь завести отдельный репозиторий с application.yaml (при этом базовая настройка приложения останется в src/main/resources)
И изменения этого файла конфигурации мгновенно попадут на ПРОД без перезапуска приложения

В env хорошо хранить креды, можно хранить какую то стартовую конфигурацию.
Вещи, которые не предполагают изменений (например, application.name), лучше просто оставить, как есть

2024-02-23 10:14 UTC, Anoldyouth commented on bot/src/test/java/edu/java/bot/BotCommandsTest.java
> +public class BotCommandsTest {
Ладно, справедливо

2024-02-23 10:19 UTC, Anoldyouth commented on bot/src/main/resources/application.yml
> +    name: ${BOT_SPRING_APPLICATION_NAME}
Окей, принял

2024-02-23 10:46 UTC, sevolchenko commented
Остальное ты же собираешься править?

2024-02-23 10:48 UTC, Anoldyouth commented
> Остальное ты же собираешься править?

Да, конечно
Просто было предложено разбивать на несколько коммитов, я что-то и залил сразу... Надо было локально оставить пока что

2024-02-23 10:53 UTC, sevolchenko commented
Отлично, что разбиваешь по коммитам

Ты можешь и пушить, просто тогда я буду ждать сообщения на платформе и только тогда приступлю к проверке

2024-02-23 11:19 UTC, Anoldyouth commented on bot/src/main/java/edu/java/bot/configuration/Chain.java
> +public interface Chain {
Поправил

2024-02-23 13:57 UTC, Anoldyouth commented
@sevolchenko 
Вроде бы все поправил
Готово к проверке

2024-02-24 10:35 UTC, sevolchenko requested changes

2024-02-24 10:35 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/ChainsUnitTest.java
> +        Action secondAction = new AbstractAction() {
Почему не использовать моки?

2024-02-24 10:35 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/util/ChainMapper.java
> +public class ChainMapper {
Может это ChainSelector или ScenarioDispatcher?

2024-02-24 10:35 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/service/Bot.java
> +            ActionFacade facade = new ActionFacade(commandsChain.getChain());
ActionFacade - компонент спринга, его не нужно создавать через new

В спринге мы стараемся все делать Stateless, поэтому перепиши так, чтобы facade на моменте вызова функции apply принимал в себя Chain (цепочку можно переименовать в сценарий).

2024-02-24 10:35 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/service/Bot.java
> +    public Bot(TelegramBot telegramBot, ChainMapper chainMapper) {
Поставь @RequiredArgsConstructor над классом и можно будет убрать этот конструктор

2024-02-24 10:35 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/util/Chain.java
> +public class Chain {
Тебе не кажется, что этот класс стал ненужным? Ты его используешь только чтобы определить бины и пару раз достать поле chain из объекта chain

Можно обойтись просто коллекций (и в конфигурации тоже просто возвращать коллекцию)

2024-02-24 10:35 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/util/response/UntrackResponse.java
> +    public UntrackResponse(Update update, List<String> urls, @NotNull String cursor) {
Перенеси конструкторы в начало класса - как и нужно по стилю кода (после полей и до функций)

2024-02-24 11:01 UTC, sevolchenko requested changes

2024-02-24 11:01 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/BotUnitTest.java
> +        var chainMapper = mock(ChainMapper.class);
можно это прям в строки 32-33 вынести

2024-02-24 11:01 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/BotUnitTest.java
> +public class BotUnitTest {
Сам класс бота написан нестестируемым - там внутри есть зависимость на mapper и на facade.

После того, как поправишь бота, поменяй и этот класс

Плюс минус должно получиться так:

- Мокируем вызов apply у фасада
- Вызываем process бота
- Проверяем, что бот отправил в телеграм именно то, что вернул apply

2024-02-24 11:01 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/ChainsUnitTest.java
> +public class ChainsUnitTest {
Это же тесты фасада - и назвать его надо FacadeTest

2024-02-24 11:01 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/ChainsUnitTest.java
> +        ActionFacade actionFacade = new ActionFacade(new Chain(testAction).getChain());
Facade получился stateful, поэтому не получается написать лаконичные тесты

Я откомментил, как его сделать лучше - ты последуешь ему и тесты будут выглядеть лучше

После этого получится Facade вынести как поле класса тестов

И дальше ты просто проверишь, что при вызове метода apply с разными цепочками, они вернут то, что нужно

2024-02-24 11:01 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/util/action/TrackAction.java
> +            return Optional.empty();
В тестах не увидел проверки на этот важный сценарий

2024-02-24 11:01 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/ActionsUnitTest.java
> +    static Arguments[] commands() {
Давай ты уберешь параметрезированные тесты и напишешь свой класс тестов под каждый Action

2024-02-24 22:45 UTC, Anoldyouth commented on bot/src/test/java/edu/java/bot/ChainsUnitTest.java
> +        Action secondAction = new AbstractAction() {
Я не знал, что можно мокать абстрактные классы
Буду знать

2024-02-25 12:23 UTC, Anoldyouth commented
Можно проверять

2024-02-25 15:33 UTC, sevolchenko requested changes

2024-02-25 15:33 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/util/action/ActionFacade.java
> +    public ResponseData applyScenario(@NotNull List<Action> actions, Update update) {
Отлично!

2024-02-25 15:33 UTC, sevolchenko commented on bot/src/main/java/edu/java/bot/configuration/ScenariosConfiguration.java
> +    public ActionFacade actionFacade() {
У тебя Фасад уже является компонентом - поэтому тут создавать бин не надо

В конфигурации нужно создавать бины, когда им нужна предварительная настройка или какие-то конкретные зависимости из контекста.

2024-02-25 15:33 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/action/TrackActionUnitTest.java
> +        assertThrows(NullPointerException.class, () -> action.apply(update));
Нормально ли, что метод падает с NPE, когда в него передают неизвестное сообщение? Может, это возможно каким то образом специфицировать?

2024-02-25 15:35 UTC, sevolchenko commented
В принципе, после ченджей на мои последние коммиты, можно мерджить

Во второй домашке ты еще не отписал, что можно проверять, поэтому не смотрю

2024-02-25 15:37 UTC, Anoldyouth commented on bot/src/test/java/edu/java/bot/action/TrackActionUnitTest.java
> +        assertThrows(NullPointerException.class, () -> action.apply(update));
Он падает, потому при Optional.empty() вызывается next, а next не определен
Так как в facade это учтено установкой UnknownCommandAction, то все хорошо (наверное)

2024-02-25 15:40 UTC, sevolchenko commented on bot/src/test/java/edu/java/bot/action/TrackActionUnitTest.java
> +        assertThrows(NullPointerException.class, () -> action.apply(update));
Давай защитимся от этого и в AbstractAction при Optional.empty() будем убеждаться, что next не null.
И в тако случае возвращать какой то дефолтный ResponseData

2024-02-25 15:47 UTC, sevolchenko commented
Билд падает, надо починить

2024-02-25 19:35 UTC, merged