homework 2
Anoldyouth/Java-Telegram-Notifications pull request #2
Opened 2024-02-24 22:36 UTC by Anoldyouth

Работа с WireMock, WebClient и Shedule

2024-02-25 12:09 UTC, sevolchenko requested changes

2024-02-25 12:09 UTC, sevolchenko commented on scrapper/src/main/java/edu/java/client/GitHubClient.java
> +    public Flux<RepositoryEvent> listRepositoryEvents(String owner, String repo, ListRepositoryEventsRequest request) {
А почему не реализовано /repos/{owner}/{repo}?

2024-02-25 12:09 UTC, sevolchenko commented on scrapper/src/main/java/edu/java/client/GitHubClient.java
> +    public Flux<RepositoryEvent> listRepositoryEvents(String owner, String repo, ListRepositoryEventsRequest request) {
Почему ты возвращаешь Flux? Мне, как пользователю твоего клиента, не хотелось бы иметь дело с реактивными сущностями

2024-02-25 12:09 UTC, sevolchenko commented on scrapper/src/main/resources/application.yml
> +    enable: false
В коде ты используешь ключ "enabled"

2024-02-25 12:10 UTC, Anoldyouth commented on scrapper/src/main/java/edu/java/client/GitHubClient.java
> +    public Flux<RepositoryEvent> listRepositoryEvents(String owner, String repo, ListRepositoryEventsRequest request) {
5 бонусное дз предполагает отслеживание типов изменений
/repos/{owner}/{repo} не содержит данной информации

2024-02-25 12:18 UTC, sevolchenko commented on scrapper/src/main/java/edu/java/client/GitHubClient.java
> +    public Flux<RepositoryEvent> listRepositoryEvents(String owner, String repo, ListRepositoryEventsRequest request) {
Кинь скрином пожалуйста, не вижу ничего про это

2024-02-25 12:19 UTC, Anoldyouth commented on scrapper/src/main/java/edu/java/client/GitHubClient.java
> +    public Flux<RepositoryEvent> listRepositoryEvents(String owner, String repo, ListRepositoryEventsRequest request) {
![image](https://github.com/Anoldyouth/Java-Telegram-Notifications/assets/83974142/ef6eef62-2276-4de2-a27d-a561dffeb334)

2024-02-25 12:20 UTC, Anoldyouth commented on scrapper/src/main/java/edu/java/client/GitHubClient.java
> +    public Flux<RepositoryEvent> listRepositoryEvents(String owner, String repo, ListRepositoryEventsRequest request) {
К сожалению, StackOverflow не позволяет получить эвенты без авторизации, поэтому там придется руками проверять

2024-02-25 15:39 UTC, Anoldyouth commented
Можно проверять

Правда, меня смущает процент покрытия тестами, который упал из-за объектов для сериализации
Насколько такие вещи должны быть покрыты тестами?

2024-02-25 15:45 UTC, sevolchenko commented on scrapper/src/main/java/edu/java/service/LinkUpdaterScheduler.java
> +@ConditionalOnProperty(name = "app.scheduler.enable", matchIfMissing = true)
Лучше было поменять название флага наоборот - оставить enabled :)

2024-02-25 15:45 UTC, sevolchenko commented on scrapper/src/main/java/edu/java/client/GitHubClient.java
> +    public Flux<RepositoryEvent> listRepositoryEvents(String owner, String repo, ListRepositoryEventsRequest request) {
А почему не авторизоваться?

2024-02-25 15:48 UTC, Anoldyouth commented on scrapper/src/main/java/edu/java/client/GitHubClient.java
> +    public Flux<RepositoryEvent> listRepositoryEvents(String owner, String repo, ListRepositoryEventsRequest request) {
![image](https://github.com/Anoldyouth/Java-Telegram-Notifications/assets/83974142/acf53838-66f5-47e2-b137-bca2b9b1d6ca)

2024-02-25 15:48 UTC, Anoldyouth commented on scrapper/src/main/java/edu/java/client/GitHubClient.java
> +    public Flux<RepositoryEvent> listRepositoryEvents(String owner, String repo, ListRepositoryEventsRequest request) {
Да и в ответе приходят все интересуемые сущности с датами, можно проверить

2024-02-25 15:51 UTC, Anoldyouth commented on scrapper/src/main/java/edu/java/client/GitHubClient.java
> +    public Flux<RepositoryEvent> listRepositoryEvents(String owner, String repo, ListRepositoryEventsRequest request) {
А с авторизацией можно было бы просто хуки установить тогда, в идеале

2024-02-25 15:53 UTC, Anoldyouth commented on scrapper/src/main/java/edu/java/service/LinkUpdaterScheduler.java
> +@ConditionalOnProperty(name = "app.scheduler.enable", matchIfMissing = true)
С точки зрения лексики, правильно будет enable
А еще лучше - is-enable

2024-02-25 15:57 UTC, Anoldyouth commented on scrapper/src/main/java/edu/java/service/LinkUpdaterScheduler.java
> +@ConditionalOnProperty(name = "app.scheduler.enable", matchIfMissing = true)
А нет, не прав

2024-02-25 16:28 UTC, sevolchenko commented
У тебя слишком разрослилсь DTO, вот другая схема пакетов, которая будет лаконичнее смотреться
`
client

++ github

++++ dto

++++ GitHubClient.java

++ stackoverflow

++++ dto

++++ StackOverflowClient.java
`

2024-02-25 16:32 UTC, sevolchenko commented
> Можно проверять
> 
> Правда, меня смущает процент покрытия тестами, который упал из-за объектов для сериализации Насколько такие вещи должны быть покрыты тестами?

ДТОшки проверять точно не надо. Тех тестов, которые ты написал, достаточно

2024-02-25 16:35 UTC, sevolchenko requested changes

2024-02-25 16:35 UTC, sevolchenko commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +    @Autowired GitHubConfig gitHubConfig;
Ты забываешь делать поля private

Если делаешь их и final, то спринг сам внедрит их и не нужно будет писать Autowired

2024-02-25 16:41 UTC, sevolchenko commented
Тк комменты сугубо косметические - поставил баллы

2024-03-03 14:51 UTC, Anoldyouth commented
Эту ветку сливаю?

2024-03-03 18:13 UTC, sevolchenko commented
Да

2024-03-03 22:16 UTC, merged